<div id="menuHeader">
	<ul class="sf-menu">
		<li class="ui-corner-all">
			<a class="ui-corner-all" href="#a">View</a>
			<ul>
				<li>
					<a href="#ab">Selected Feature</a>
					<ul>
						<li class="current"><a href="#" id="fProperties">Properties...</a></li>
						<li class="current"><a href="#" id="aaOfFeature">Amino Acids...</a></li>
						<li class="current"><a href="#" id="basesOfFeature">Bases...</a></li>
						<li class="current"><a href="#" id="basesOfFeature">Hide/Show</a></li>
					</ul>
				</li>
				<li>
					<a href="#" id="gotoGene">Find...</a>
				</li>
				<li>
					<a href="#ab">Stop codons</a>
					<ul>
						<li class="current"><a href="#" id="stopCodonToggle">show/hide</a></li>
					</ul>
				</li>
				<li id='bamFiles'>
					<a href="#ab">BAM</a>
					<ul>
						<li class="current"><a href="#" id="bamToggle">none</a></li>
					</ul>
				</li>
			</ul>
		</li>
		<li class="ui-corner-all">
			<a class="ui-corner-all" href="#">Graph</a>
			<ul>
				<li>
					<a href="#" id="gcGraphToggle">GC content %</a>
				</li>
				<li>
					<a href="#" id="agGraphToggle">AG content %</a>
				</li>
				<li>
					<a href="#" id="otherGraphToggle">Database Loaded</a>
				</li>
			</ul>
		</li>
	</ul>
	</div>
	
	<div id="popupContact"><div id="popupTxt"></div></div>  
	
    <div id="ticks"></div>
	<div class="fwdFrames"></div>
	<div class="bwdFrames"></div>
	<div class="strands"></div>
		
	<div id="bam" class="holder"></div>
	<div id="featureDisplays" class="holder"></div>
	<div id="comparisons" class="holder"></div>
	<div id="stop_codons" class="holder"></div>
	<div id="sequence" class="holder"></div>
	<div id="translation" class="holder"></div>
	<div id="features"></div>

	<div id="organismSelector"></div>
	<div id="srcFeatureSelector"></div>

	<div id="slider_container"></div>
	<div id="slider_vertical_container"></div>
	<div id="buttons"></div>

	<div id="graph"></div>
	<div id="featureList"></div>

	<div id="logger"></div>
	<div id="rightDraggableEdge"></div>
	<div id="properties" class="holder" style="display: none;"></div>
	<div id="matchProps" class="holder" style="display: none;"></div>